"use strict";
const canvas=document.querySelector("#view"),gl=canvas.getContext("webgl"),status=document.querySelector("#status");let pointVertices=[],visualPath=[],gpsPath=[],yaw=.6,pitch=.45,zoom=2.8,drag=false,last=[0,0],worldScale=1,measuring=false,selected=[];
if(!gl){status.textContent="WebGL is unavailable.";throw new Error("WebGL unavailable")}
const vs="attribute vec3 p;uniform mat4 m;uniform float size;void main(){gl_Position=m*vec4(p,1.);gl_PointSize=size;}",fs="precision mediump float;uniform vec3 color;void main(){gl_FragColor=vec4(color,1.);}";
function shader(t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);return x}const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);gl.useProgram(program);
const pos=gl.getAttribLocation(program,"p"),mat=gl.getUniformLocation(program,"m"),color=gl.getUniformLocation(program,"color"),size=gl.getUniformLocation(program,"size");
function parsePly(text){const lines=text.split(/\r?\n/),end=lines.indexOf("end_header"),head=lines.find(x=>x.startsWith("element vertex ")),count=head?Number(head.split(" ")[2]):0;if(end<0||!count)throw Error("Viewer supports ASCII PLY");const out=[];for(let i=end+1;i<Math.min(lines.length,end+1+count);i++){const v=lines[i].trim().split(/\s+/).map(Number);if(v.length>=3)out.push(v[0],v[1],v[2])}return out}
function centerAll(groups){const all=groups.flat();if(!all.length)return;const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<all.length;i+=3)for(let k=0;k<3;k++){min[k]=Math.min(min[k],all[i+k]);max[k]=Math.max(max[k],all[i+k])}const c=min.map((x,k)=>(x+max[k])/2),span=Math.max(...max.map((x,k)=>x-min[k]))||1;worldScale=span;for(const g of groups)for(let i=0;i<g.length;i+=3)for(let k=0;k<3;k++)g[i+k]=(g[i+k]-c[k])/span}
function matrix(){const a=canvas.width/canvas.height,f=1/Math.tan(.5),cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),z=-zoom;return new Float32Array([f/a*cy,f*sp*sy,-cp*sy,-sp*sy*z,0,f*cp,sp,-sp*z,f/a*sy,-f*sp*cy,cp*cy,-cp*cy*z,0,0,-1,zoom])}
function draw(v,mode,rgb,n=2){if(!v.length)return;const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.STREAM_DRAW);gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,3,gl.FLOAT,false,0,0);gl.uniform3fv(color,rgb);gl.uniform1f(size,n);gl.drawArrays(mode,0,v.length/3);gl.deleteBuffer(b)}
function render(){const d=devicePixelRatio||1,w=canvas.clientWidth*d,h=canvas.clientHeight*d;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.clearColor(.03,.05,.08,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.uniformMatrix4fv(mat,false,matrix());if(points.checked)draw(pointVertices,gl.POINTS,[.46,.84,1],2*d);if(visual.checked)draw(visualPath,gl.LINE_STRIP,[.47,.93,.61]);if(gps.checked)draw(gpsPath,gl.LINE_STRIP,[1,.8,.4]);draw(selected.flat(),gl.POINTS,[1,.25,.2],9*d);requestAnimationFrame(render)}
async function load(){const meta=await fetch("/api/mission").then(r=>r.json());mission.textContent=meta.name;const layer=meta.layers.processed||meta.layers.raw||meta.layers.sparse;if(layer)pointVertices=parsePly(await fetch(layer).then(r=>r.text()));if(meta.layers.trajectory){const geo=await fetch(meta.layers.trajectory).then(r=>r.json());for(const f of geo.features){const a=f.geometry.coordinates.flat();if(f.properties.trajectory==="visual_aligned")visualPath=a;else if(f.properties.trajectory==="gps_supplied")gpsPath=a}}centerAll([pointVertices,visualPath,gpsPath]);status.textContent+="\n"+pointVertices.length/3+" points loaded"}load().catch(e=>status.textContent=e.message);
canvas.onpointerdown=e=>{drag=true;last=[e.clientX,e.clientY]};onpointerup=()=>drag=false;onpointermove=e=>{if(drag){yaw+=(e.clientX-last[0])*.008;pitch=Math.max(-1.4,Math.min(1.4,pitch+(e.clientY-last[1])*.008));last=[e.clientX,e.clientY]}};canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(1.1,Math.min(10,zoom*Math.exp(e.deltaY*.001)))};reset.onclick=()=>{yaw=.6;pitch=.45;zoom=2.8};render();

measure.onclick=()=>{measuring=true;selected=[];status.textContent="Click two observed points"};
canvas.onclick=e=>{if(!measuring||!pointVertices.length)return;const m=matrix(),rect=canvas.getBoundingClientRect(),tx=(e.clientX-rect.left)/rect.width*2-1,ty=1-(e.clientY-rect.top)/rect.height*2;let best=null,bestD=Infinity;for(let i=0;i<pointVertices.length;i+=3){const x=pointVertices[i],y=pointVertices[i+1],z=pointVertices[i+2],cx=m[0]*x+m[4]*y+m[8]*z+m[12],cy=m[1]*x+m[5]*y+m[9]*z+m[13],cw=m[3]*x+m[7]*y+m[11]*z+m[15];if(cw<=0)continue;const d=(cx/cw-tx)**2+(cy/cw-ty)**2;if(d<bestD){bestD=d;best=[x,y,z]}}if(best){selected.push(best);if(selected.length===2){const d=Math.hypot(selected[0][0]-selected[1][0],selected[0][1]-selected[1][1],selected[0][2]-selected[1][2])*worldScale;status.textContent="Measured distance: "+d.toFixed(3)+" m";measuring=false}}};
