[server]
maxUploadSize = 8192
headless = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#38BDF8"
backgroundColor = "#070B13"
secondaryBackgroundColor = "#0F172A"
textColor = "#F1F5F9"
baseRadius = "0.6rem"
buttonRadius = "0.5rem"
font = "sans serif"
